name: Playwright Test Automation

on:
  repository_dispatch:
    types: [deploy]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Automation Repository
    - name: Checkout Automation Repo
      uses: actions/checkout@v4
