name: Playwright Test Automation

on:
  repository_dispatch:
    types: [deploy]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Automation Repository
    - name: Checkout Automation Repo
      uses: actions/checkout@v4

    # Step 2: Install System Dependencies
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libopus0 \
          libvpx7 \
          libevent-2.1-7 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          gstreamer1.0-libav \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          libgstcodecparsers-1.0-0 \
          libflite1 \
          libavif13 \
          libharfbuzz-icu0 \
          libhyphen0 \
          libmanette-0.2-0 \
          libgles2-mesa \
          x264

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Run Playwright Tests
    - name: Run Playwright Tests
      run: npx playwright test
