name: Playwright Test Automation

on:
  repository_dispatch:
    types: [deploy]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Automation Repository
    - name: Checkout Automation Repo
      uses: actions/checkout@v4

    # Step 2: Install System Dependencies
    - name: Install Playwright Dependencies
      run: npx playwright install-deps

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Install Browser
    - name: Install Browser
      run: npx playwright install

    # Step 5: Wait for Website to Start
    - name: Wait for Website
      run: |
        for i in {1..30}; do
          curl -s http://localhost:3000 && break
          echo "Waiting for the website to start..."
          sleep 2
        done

    # Step 6: Run Playwright Tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Step 7: Generate Allure Report
    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    # Step 8: Upload Allure Report as Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
